### ISSUE TITLE
Blocked e-mails from kannashoes.com

### ISSUE THREAD

**Issue by CyberCr33p** [mxroute/rspamd_rules#23]
Hello,

I use your lists to block incoming spam.

Today a customer contact me and told me that he can't get e-mails from @kannashoes.com

Can you please remove the word `kannashoes` from blacklisted-sender-strings.map ?

Thank you in advance.

**Comment by mxroute** [comment]
I couldn't find any recent cases of the emails that caused them to be added here, so I'll go ahead and remove them.
