### ISSUE TITLE
Unable to parse regex from subject-spam.map

### ISSUE THREAD

**Issue by justrudra** [mxroute/rspamd_rules#6]
Hi,
Need some help here. I am using rspamd version 2.7, and I am using these rspamd rules as well. As the subject reads, rspamd is not able to parse regex from the file subject-spam.map. please see the attached image.
Also upon executing the command `rspamadm configtest` I get these messages:
`symbol 'R_RATELIMIT' has its score defined but there is no corresponding rule registered`
`symbol 'NO_BOUNCE' has its score defined but there is no corresponding rule registered`
`symbol 'IP_SCORE' has its score defined but there is no corresponding rule registered`
`syntax OK`

How to fix this?

![errors](https://user-images.githubusercontent.com/25903836/125634654-87e81bc8-bf15-4309-8717-0013960166a1.png)

**Comment by mxroute** [comment]
Interesting. Investigating.

**Comment by mxroute** [comment]
I think it was my handling of certain characters in the email subjects. In this case these two lines were honestly designed to send a message to a spammer: "I see you, I can parse you." I didn't think they'd ever be extremely effective, and it seems they weren't. Future iterations of the technique have done better, I'm going to pull these old lines.

Thanks!
