### ISSUE TITLE
blacklisted-sender-strings.map 'cannot parse regexp'

### ISSUE THREAD

**Issue by briellie** [mxroute/rspamd_rules#9]
rspamd is reporting a problem with line 138 of blacklisted-sender-strings.map.  Looks like an error with the regex - I'm not at my normal desktop or I'd run it through my parser and fix it.

https://github.com/mxroute/rspamd_rules/blob/409b1220cea3465125735359752fc00024639aef/lists/blacklisted-sender-strings.map#L138

**Comment by mxroute** [comment]
Hmm, good catch. It may take me a bit today to find out where I went wrong. It was all generated by a one liner from parsing the logs of an attack.

**Comment by mxroute** [comment]
I think it's fixed. You seeing the same? It seems like the entry was just too long, and breaking it up seemed to bring things back in order.

**Comment by briellie** [comment]
I think its fixed, thanks!
